const fs=require('fs');const vm=require('vm');const assert=require('assert');
const sandbox={globalThis:{}};vm.createContext(sandbox);
vm.runInContext(fs.readFileSync(__dirname+'/MM_Acquisitions.purchase.logic.js','utf8'),sandbox,{filename:'MM_Acquisitions.purchase.logic.js'});
const logic=sandbox.globalThis.MMTornAcquisitionLedger;assert(logic);
const ts=Math.floor(Date.now()/1000)-60;
const rows=logic.parseAcquisitionLog({id:'log1',timestamp:ts,data:{items:[{id:26,qty:2}],cost_total:2000,seller_id:7}},'Bazaar',{'26':{name:'AK-47'}});
assert.strictEqual(rows.length,1);assert.strictEqual(rows[0].unitCost,1000);assert.strictEqual(rows[0].quantity,2);
const proc=logic.ensureProcurement({catalog:{'26':{name:'AK-47'}}});
assert.strictEqual(logic.mergeAcquisitionLogRows(proc,[{id:'log1',timestamp:ts,data:{items:[{id:26,qty:2}],cost_total:2000}}],'Bazaar'),1);
assert.strictEqual(logic.mergeAcquisitionLogRows(proc,[{id:'log1',timestamp:ts,data:{items:[{id:26,qty:2}],cost_total:2000}}],'Bazaar'),0);
assert.strictEqual(proc.acquisitions.length,1);

const userSource=fs.readFileSync(__dirname+'/MM_Acquisitions.user.js','utf8');
new Function(userSource);
assert(userSource.includes('// @version      8.0.0-alpha.18'));
assert(userSource.includes('cdn.jsdelivr.net/gh/tuccijr75/privacy-policy@6e409ed0849fd15378ed513d76a8b954c766660c/modular-suite/core/MM_Torn_Core.js'));
assert(userSource.includes('cdn.jsdelivr.net/gh/tuccijr75/privacy-policy@6e409ed0849fd15378ed513d76a8b954c766660c/modular-suite/acquisitions/MM_Acquisitions.logic.js'));
assert(userSource.includes('cdn.jsdelivr.net/gh/tuccijr75/privacy-policy@6e409ed0849fd15378ed513d76a8b954c766660c/modular-suite/acquisitions/MM_Acquisitions.live.js'));
assert(userSource.includes('cdn.jsdelivr.net/gh/tuccijr75/privacy-policy@6e409ed0849fd15378ed513d76a8b954c766660c/modular-suite/acquisitions/MM_Acquisitions.ranked.logic.js'));
assert(!userSource.includes('// @updateURL'));
assert(!userSource.includes('// @downloadURL'));
assert(userSource.includes('async function autoRefreshAcquisitions'));
assert(userSource.includes('AUTO_REFRESH_MS=60_000'));
assert(userSource.includes('PURCHASE_STALE_MS=120_000'));
assert(userSource.includes('OPPORTUNITY_STALE_MS=300_000'));
assert(userSource.includes('TRAVEL_FRESH_MS=300_000'));
assert(userSource.includes('TRAVEL_STALE_MS=900_000'));
assert(userSource.includes('Market purchase deferred: '));
assert(userSource.includes('Stale/unknown travel data is not used for recommendations.'));
assert(userSource.includes('grid-template-columns:repeat(auto-fit,minmax(135px,1fr))'));
assert(userSource.includes('Min confidence %'));
assert(userSource.includes('Rule-Qualified Deals'));
assert(userSource.includes('All Torn Items'));
assert(userSource.includes('Enter item name or ID'));
assert(userSource.includes('Find Best Price'));
assert(userSource.includes('data-catalog-find'));
assert(userSource.includes("data-acq-view=\"items\""));
assert(userSource.includes('ITEM_PAGE_SIZE=75'));
assert(userSource.includes('CATALOG_STALE_MS=24*60*60*1000'));
assert(userSource.includes('MM_Acquisitions.ranked.logic.js'));
assert(userSource.includes('Ranked Weapon Profit Scout'));
assert(userSource.includes('Auction prices are current bids, not guaranteed purchase prices.'));
assert(userSource.includes('Current bid <b>'));
assert(userSource.includes('Break-even ceiling '));
assert(userSource.includes('Max bid @ '));
assert(userSource.includes('Provisional ROI at current bid'));
assert(userSource.includes('auctions use watch score'));
assert(userSource.includes("watch '+Number(row.auctionWatchScore||0)+'/100"));
assert(userSource.includes("Number(b.sortScore||0)-Number(a.sortScore||0)"));
assert(userSource.includes('UNDER BB FLOOR'));
assert(userSource.includes('futureDuration(row.endsAt)'));
assert(userSource.includes('Pricelist Universe'));
assert(userSource.includes('Pricelist Universe Scan'));
assert(userSource.includes('data-pricelist-verify'));
assert(userSource.includes('RANKED_LIVE_STALE_MS=300_000'));
assert(userSource.includes('PRICELIST_STALE_MS=3600_000'));
assert(userSource.includes("url.searchParams.set('listing','auction')"));
assert(!userSource.includes('sid=ItemMarket#/market/view=auctionHouse'));
assert(userSource.includes('Update Pricelist'));
assert(userSource.includes('Refresh Ranked'));
assert(userSource.includes('Analyze Visible'));
assert(userSource.includes('Primary'));
assert(userSource.includes('Secondary'));
assert(userSource.includes('Melee'));
assert(userSource.includes('Bazaar observed'));
assert(userSource.includes('Bazaar low <b>'));
assert(userSource.includes('option value="bazaar"'));
assert(userSource.includes('option value="item-market"'));
assert(userSource.includes('Compare Bazaar / Market'));
assert(userSource.includes('Cost unavailable'));
assert(userSource.includes('shop cost unavailable in current TornW3B table; preserved as travel evidence'));
assert(userSource.includes('Travel profit '));
assert(userSource.includes('data-travel-compare'));
assert(userSource.includes('Live exit '));
assert(userSource.includes('reference only; not used as live exit'));
assert(userSource.includes('aggregate Bazaar evidence; seller is re-resolved before routing'));
assert(userSource.includes("Bazaar '+esc(age(f.weav3rGeneratedAt))"));
assert(userSource.includes("id:'acquisitions'"));
assert(!userSource.includes("id:'ranked-acquisitions'"));
assert(userSource.includes('Verify & Buy and final purchase remain manual'));
console.log('MM_Acquisitions purchase-ledger + automation regression tests: PASS');

const pdaSource=fs.readFileSync(__dirname+'/MM_Acquisitions.pda.user.js','utf8');
new Function(pdaSource);
const pdaHeader=pdaSource.slice(0,pdaSource.indexOf('// ==/UserScript=='));
assert(pdaSource.includes('// @version      8.0.0-alpha.18-pda.5'));
assert(!pdaHeader.includes('@require'));
assert(!pdaSource.includes('globalThis.GM_getValue=function'));
assert(pdaSource.includes("const __MM_PDA_API_KEY='###PDA-APIKEY###';"));
assert(!pdaSource.includes('__MM_PDA_API_KEY__'));
assert(pdaSource.includes("const apiKey=()=>{const saved=String(GM_getValue(API_KEY,'')||'').trim();if(saved)return saved;const pda=String(__MM_PDA_API_KEY||'').trim();"));
assert(pdaSource.includes("globalThis.__MM_ACQ_PDA_STAGE='boot'"));
assert(pdaSource.includes("globalThis.__MM_ACQ_PDA_STAGE='adapter'"));
assert(pdaSource.includes("globalThis.__MM_ACQ_PDA_STAGE='ui-ready'"));
assert(pdaSource.includes("if(core?.registerDockLauncher&&!globalThis.__MM_TORN_PDA__)"));
assert(pdaSource.includes('position:fixed;right:10px;bottom:86px;'));
assert(pdaSource.includes('async function pdaSharedGet'));
assert(pdaSource.includes("typeof PDA_storage!=='undefined'&&PDA_storage&&typeof PDA_storage.get==='function'"));
assert(pdaSource.includes('await PDA_storage.set(String(key),value)'));
assert(pdaSource.includes('const maybeReturn=async count=>'));
assert(pdaSource.includes('const feed=await loadTravelFeed();'));
assert(pdaSource.includes('const feed=await writeTravelFeed(rows,Date.now());'));
assert(pdaSource.includes('await beginTravelCapture();'));

const pdaAdapterSource=fs.readFileSync(__dirname+'/MM_Acquisitions.pda.adapter.js','utf8');
assert(!pdaAdapterSource.includes('globalThis.GM_getValue=function'));
assert(!pdaAdapterSource.includes('__MM_PDA_API_KEY__'));
assert(pdaAdapterSource.includes("typeof PDA_storage!=='undefined'&&PDA_storage&&typeof PDA_storage.get==='function'"));

const pdaBuilder=fs.readFileSync(__dirname+'/build_pda_bundle.py','utf8');
assert(pdaBuilder.includes('def replace_once('));
assert(pdaBuilder.includes('default=5'));
assert(pdaBuilder.includes('PDA cross-origin Travel storage'));
assert(pdaBuilder.includes("const __MM_PDA_API_KEY='###PDA-APIKEY###';"));


const liveSource=fs.readFileSync(__dirname+'/MM_Acquisitions.live.js','utf8');
new Function(liveSource);
assert(liveSource.includes('function resolveProcurementItemId'));
assert(liveSource.includes('async function procurementSourceOptions'));
assert(liveSource.includes('async function routeProcurementRequest'));
assert(liveSource.includes("source:'Bazaar'"));
assert(liveSource.includes('function canonicalRankedSource'));
assert(liveSource.includes("lowestSource:Number(row?.lowest_price || 0)>0?'Bazaar':'Unknown'"));
assert(liveSource.includes('TornW3B Bazaar + Item Market + Auction APIs'));
assert(liveSource.includes('function selectedItemExitEvidence'));
assert(liveSource.includes("source:'Bazaar aggregate'"));
assert(liveSource.includes("source:'Overseas'"));
assert(liveSource.includes('priceKnown:Number(bestTravel.shopCost||0)>0'));
assert(liveSource.includes('travelEvidence:true'));
assert(liveSource.includes('aggregateBazaarLow*1.35'));
assert(!liveSource.includes("route:'Live snapshot'"));
assert(liveSource.includes("const itemMarketAsk=Math.max(0,Number(snap?.itemMarket?.lowest||0));"));
assert(liveSource.includes("const itemMarketNet=Math.floor(itemMarketAsk*(1-ITEM_MARKET_FEE_RATE));"));
assert(liveSource.includes("source:'Item Market'"));
assert(liveSource.includes("source:'Overseas'"));
assert(liveSource.includes("reason:'overseas-recommended'"));
assert(liveSource.includes('function normalizeTornCatalog'));
assert(liveSource.includes('async function refreshItemCatalog'));
assert(liveSource.includes("source:'Torn Shop'"));
assert(liveSource.includes("reason:'shop-recommended'"));
assert(liveSource.includes('async function refreshPricelist'));
assert(liveSource.includes('async function refreshRankedLive'));
assert(liveSource.includes('async function refreshRankedHistory'));
assert(liveSource.includes("'/ranked-weapons'"));
assert(liveSource.includes("'/auction/listings'"));
assert(liveSource.includes("'/auctionhouse?limit=100"));
assert(liveSource.includes('TornW3B Pricelist API'));
assert(liveSource.includes('Torn API finished Auction House'));

const userSourceArmory=fs.readFileSync(__dirname+'/MM_Acquisitions.user.js','utf8');
new Function(userSourceArmory);
assert(userSourceArmory.includes('// @version      8.0.0-alpha.18'));
assert(userSourceArmory.includes('MM_Acquisitions.live.js'));
assert(userSourceArmory.includes("type!=='armory-acquisition-request'"));
assert(userSourceArmory.includes('Faction Armory request: '));
assert(userSourceArmory.includes('Compare Sources'));
assert(userSourceArmory.includes('Find Best Source'));
assert(userSourceArmory.includes('Final purchase remains manual.'));
assert(userSourceArmory.includes('Open Travel Agency'));
assert(userSourceArmory.includes('https://www.torn.com/travelagency.php'));
console.log('MM_Acquisitions armory procurement routing regression: PASS');
