const fs=require('fs');const vm=require('vm');const assert=require('assert');
const sandbox={globalThis:{}};vm.createContext(sandbox);
vm.runInContext(fs.readFileSync(__dirname+'/MM_Customers.logic.js','utf8'),sandbox,{filename:'MM_Customers.logic.js'});
const logic=sandbox.globalThis.MMTornCustomersLogic;assert(logic);
const now=Date.now();
const db=logic.ensureCustomerSlice({operations:{inventoryRoi:{listings:{26:{id:'26',name:'AK-47',quantity:2,price:12000}}}}});
const imported=logic.importSalesEntries(db,[{id:'sale-1',timestamp:Math.floor((now-1000)/1000),details:{id:1226},data:{buyer:{id:123,name:'Buyer'},item_id:26,item_name:'AK-47',quantity:1,cost_total:60000}}]);
assert.strictEqual(imported.imported,1);assert.strictEqual(db.customers['123'].spent,60000);
const coupon=logic.issueCoupon(db,'123',new Date(now-2000).toISOString());
const q=logic.couponQualification(db,coupon,now);assert.strictEqual(q.qualified,true);assert.strictEqual(q.cashback,5000);
const refund=logic.createRefund(db,'123',new Date(now).toISOString());assert.strictEqual(refund.status,'pending');
logic.completeRefund(db,refund.id,new Date(now+1000).toISOString());assert.strictEqual(db.coupons['123'].uses,1);
logic.subscribeCustomer(db,'123');assert.strictEqual(logic.currentBazaarRows(db,db.subscribers['123']).length,1);

const userSrc=fs.readFileSync(__dirname+'/MM_Customers.user.js','utf8');
assert.doesNotThrow(()=>new Function(userSrc));
assert(userSrc.includes("const VERSION='8.0.0-alpha.15';"));
assert(userSrc.includes("const PENDING_COMPOSE_KEY='mm_customers_pending_compose_v1';"));
assert(userSrc.includes('function brandedMessageHtml'));
assert(userSrc.includes('function fillMessageComposer'));
assert(userSrc.includes('bodyHtml:brandedMessageHtml'));
assert(!userSrc.includes('data-restock-sent'));
assert(userSrc.includes('data-restock-dismiss'));
assert(userSrc.includes('New Customers ('));
assert(userSrc.includes('async function repairUsernames'));
assert(userSrc.includes('function installMessageSendDetector'));
assert(userSrc.includes('function completeTrackedSend'));
assert(userSrc.includes("const DELIVERY_RECEIPTS_KEY='mm_customers_delivery_receipts_v1';"));
assert(userSrc.includes('function newSentConfirmationEvidence'));
assert(userSrc.includes('function deliveryFingerprintCount'));
assert(userSrc.includes('event.isTrusted'));
assert(userSrc.includes('event.submitter'));
assert(userSrc.includes("state:'send-unconfirmed'"));
assert(userSrc.includes('function recentFirstContactRecoveryRows'));
assert(userSrc.includes('Restore to New Customers'));
assert(!userSrc.includes("messageSentConfirmationVisible()||!location.hash.includes('compose')||!composeStillVisible"));
assert(userSrc.includes("window.location.assign(url)"));
assert(userSrc.includes("const PENDING_SEND_KEY='mm_customers_pending_send_v1';"));
assert(userSrc.includes('AUTO_SYNC_MS=60_000'));
assert(!userSrc.includes('data-mark-welcome'));
assert(!userSrc.includes('navigator.clipboard'));
assert(!userSrc.includes('copyAndOpenMessage'));
console.log('MM_Customers logic + verified-delivery automation/composer regression tests: PASS');
const userSourceRich=fs.readFileSync(__dirname+'/MM_Customers.user.js','utf8');
new Function(userSourceRich);
assert(userSourceRich.includes("const VERSION='8.0.0-alpha.15';"));
assert(userSourceRich.includes('function richComposerHasBranding'));
assert(userSourceRich.includes('function composeEditorSurfaceReady'));
assert(userSourceRich.includes('Waiting for Torn rich editor… branded message will retry automatically.'));
assert(userSourceRich.includes('Never toggle while Torn'));
assert(userSourceRich.includes('recipient + branded formatting verified'));
assert(!userSourceRich.includes('setEditorContent(body,payload.body,payload.bodyHtml)'));
console.log('MM Customers rich-composer resilience regression: PASS');

const userSourceRefunds=fs.readFileSync(__dirname+'/MM_Customers.user.js','utf8');
new Function(userSourceRefunds);
assert(userSourceRefunds.includes("const VERSION='8.0.0-alpha.15';"));
assert(userSourceRefunds.includes('function cashbackEligibleRows'));
assert(userSourceRefunds.includes('function cashbackEligibilityReminderMessage'));
assert(userSourceRefunds.includes('Send Cashback Reminder'));
assert(userSourceRefunds.includes('QUALIFYING PURCHASE'));
assert(userSourceRefunds.includes('Refund amount: '));
assert(userSourceRefunds.includes("composeMessage(id,msg.subject,msg.body,msg.bodyHtml,{kind:'reminder'})"));
assert(userSourceRefunds.includes('No customers are currently eligible for cashback.'));
console.log('MM Customers refund eligibility reminder regression: PASS');

const userSourceCashbackRich=fs.readFileSync(__dirname+'/MM_Customers.user.js','utf8');
new Function(userSourceCashbackRich);
assert(userSourceCashbackRich.includes("const VERSION='8.0.0-alpha.15';"));
assert(userSourceCashbackRich.includes("CASHBACK REMINDER|QUALIFYING PURCHASE|YOUR CASHBACK|SEND YOUR COUPON"));
assert(userSourceCashbackRich.includes('Draft was NOT downgraded to plain text.'));
assert(userSourceCashbackRich.includes('Preparing branded message… do not send until this notice disappears.'));
assert(!userSourceCashbackRich.includes('plain text fallback after rich-editor retries failed'));
console.log('MM Customers cashback reminder rich-verification regression: PASS');

const userSourceAnon=fs.readFileSync(__dirname+'/MM_Customers.user.js','utf8');
new Function(userSourceAnon);
assert(userSourceAnon.includes("const VERSION='8.0.0-alpha.15';"));
assert(userSourceAnon.includes("for(const selector of ['textarea'"));
assert(userSourceAnon.includes('anonymous textarea'));
assert(userSourceAnon.includes('function brandedMarkersFromHtml'));
assert(userSourceAnon.includes("CASHBACK REMINDER','QUALIFYING PURCHASE','YOUR CASHBACK','SEND YOUR COUPON"));
assert(userSourceAnon.includes('waitForRichBranding(payload.bodyHtml,1200)'));
console.log('MM Customers anonymous source textarea regression: PASS');

const userSourceScope=fs.readFileSync(__dirname+'/MM_Customers.user.js','utf8');
new Function(userSourceScope);
assert(userSourceScope.includes("const VERSION='8.0.0-alpha.15';"));
assert(userSourceScope.includes('function composeAreaTextarea'));
assert(userSourceScope.includes('function looksLikeHtmlSource'));
assert(userSourceScope.includes('allowFreshAnonymous&&!before.has(el)'));
assert(userSourceScope.includes('function setSourceEditorHtml'));
assert(userSourceScope.includes('likelyTornSourceEditor(new Set(),false)'));
assert(userSourceScope.includes('PENDING_COMPOSE_TTL_MS=30*60*1000'));
assert(userSourceScope.includes('bodyHtml:payload.bodyHtml'));
console.log('MM Customers source textarea scoping regression: PASS');

const userSourceTransport=fs.readFileSync(__dirname+'/MM_Customers.user.js','utf8');
new Function(userSourceTransport);
assert(userSourceTransport.includes("const VERSION='8.0.0-alpha.15';"));
assert(userSourceTransport.includes('COMPOSE_ROUTE_RECOVERY_MS=5*60*1000'));
assert(userSourceTransport.includes('COMPOSE_SURFACE_STABLE_MS=350'));
assert(userSourceTransport.includes('COMPOSE_POST_FILL_VERIFY_MS=500'));
assert(userSourceTransport.includes('COMPOSE_FILL_TIMEOUT_MS=45_000'));
assert(userSourceTransport.includes('function findComposeRecipientInput'));
assert(userSourceTransport.includes('function recipientMatchesPayload'));
assert(userSourceTransport.includes("value.includes('['+id+']')"));
assert(userSourceTransport.includes('function canonicalComposeUrl'));
assert(userSourceTransport.includes('routeRecovery:genericRecovery'));
assert(userSourceTransport.includes("String(tracked.state||'awaiting-send')==='awaiting-send'"));
assert(userSourceTransport.includes('function clearMatchingPendingCompose'));
assert(userSourceTransport.includes('composeFillGeneration'));
assert(userSourceTransport.includes("if(id&&(!xid||!recipientMatchesPayload(pending,findComposeRecipientInput())))return false;"));
assert(userSourceTransport.includes("recipientName:pending.recipientName||state?.customers?.[String(pending.playerId||'')]?.name||''"));
console.log('MM Customers recipient-aware compose transport regression: PASS');

const userSourceRepair=fs.readFileSync(__dirname+'/MM_Customers.user.js','utf8');
new Function(userSourceRepair);
assert(userSourceRepair.includes("const VERSION='8.0.0-alpha.15';"));
assert(userSourceRepair.includes('function matchingBrandedTable'));
assert(userSourceRepair.includes('function repairRenderedBrandedTable'));
assert(userSourceRepair.includes("replace(/\\bCSHBACK\\b/g,'CASHBACK')"));
assert(userSourceRepair.includes('table.insertBefore(bannerRow.cloneNode(true),table.firstChild)'));
assert(userSourceRepair.includes('A complete matching branded table is authoritative'));
console.log('MM Customers cashback heading repair regression: PASS');
