const fs=require('fs');const vm=require('vm');const assert=require('assert');
const sandbox={globalThis:{}};vm.createContext(sandbox);
vm.runInContext(fs.readFileSync(__dirname+'/MM_Customers.logic.js','utf8'),sandbox,{filename:'MM_Customers.logic.js'});
const logic=sandbox.globalThis.MMTornCustomersLogic;assert(logic);
const now=Date.now();
const db=logic.ensureCustomerSlice({operations:{inventoryRoi:{listings:{26:{id:'26',name:'AK-47',quantity:2,price:12000}}}}});
const imported=logic.importSalesEntries(db,[{id:'sale-1',timestamp:Math.floor((now-1000)/1000),details:{id:1226},data:{buyer:{id:123,name:'Buyer'},item_id:26,item_name:'AK-47',quantity:1,cost_total:60000}}]);
assert.strictEqual(imported.imported,1);assert.strictEqual(db.customers['123'].spent,60000);
const coupon=logic.issueCoupon(db,'123',new Date(now-2000).toISOString());
const q=logic.couponQualification(db,coupon,now);assert.strictEqual(q.qualified,true);assert.strictEqual(q.cashback,5000);
const refund=logic.createRefund(db,'123',new Date(now).toISOString());assert.strictEqual(refund.status,'pending');
logic.completeRefund(db,refund.id,new Date(now+1000).toISOString());assert.strictEqual(db.coupons['123'].uses,1);
logic.subscribeCustomer(db,'123');assert.strictEqual(logic.currentBazaarRows(db,db.subscribers['123']).length,1);

const userSrc=fs.readFileSync(__dirname+'/MM_Customers.user.js','utf8');
assert.doesNotThrow(()=>new Function(userSrc));
assert(userSrc.includes("const VERSION='8.0.0-alpha.8';"));
assert(userSrc.includes("const PENDING_COMPOSE_KEY='mm_customers_pending_compose_v1';"));
assert(userSrc.includes('function brandedMessageHtml'));
assert(userSrc.includes('function fillMessageComposer'));
assert(userSrc.includes('bodyHtml:brandedMessageHtml'));
assert(userSrc.includes('data-restock-sent'));
assert(userSrc.includes('data-restock-dismiss'));
assert(userSrc.includes('New Customers ('));
assert(userSrc.includes('async function repairUsernames'));
assert(userSrc.includes('function installMessageSendDetector'));
assert(userSrc.includes('function completeTrackedSend'));
assert(userSrc.includes("window.location.assign(url)"));
assert(userSrc.includes("const PENDING_SEND_KEY='mm_customers_pending_send_v1';"));
assert(userSrc.includes('AUTO_SYNC_MS=60_000'));
assert(!userSrc.includes('data-mark-welcome'));
assert(!userSrc.includes('navigator.clipboard'));
assert(!userSrc.includes('copyAndOpenMessage'));
console.log('MM_Customers logic + automation/composer regression tests: PASS');
const userSourceRich=fs.readFileSync(__dirname+'/MM_Customers.user.js','utf8');
new Function(userSourceRich);
assert(userSourceRich.includes("const VERSION='8.0.0-alpha.8';"));
assert(userSourceRich.includes('function richComposerHasBranding'));
assert(userSourceRich.includes('richFailures<3'));
assert(userSourceRich.includes('Waiting for Torn rich editor… branded message will retry automatically.'));
assert(userSourceRich.includes('plain text fallback after rich-editor retries failed'));
assert(userSourceRich.includes('can occasionally carry source'));
console.log('MM Customers rich-composer resilience regression: PASS');
